LCH-4486-1.x: Ability to take snapshots from plexus
acquia/content-hub-php pull request #116
Opened 2020-10-26 09:42 UTC by ankitsingh0188

2020-11-03 15:03 UTC, Ateee89 requested changes

2020-11-03 15:03 UTC, Ateee89 commented on src/ContentHub.php
> +      return self::getResponseJson($this->get('snapshots'));
I am not sure how can this work. getResponseJson() function first parameter should be a RequestInterface. $this->get('snapshots') will return a ResponseInterface

2020-11-03 15:03 UTC, Ateee89 commented on src/ContentHub.php
> +      return self::getResponseJson($this->post('snapshots'));
Same here

2020-11-03 15:03 UTC, Ateee89 commented on src/ContentHub.php
> +      return self::getResponseJson($this->delete("snapshots/$name"));
Same here

2020-11-03 15:03 UTC, Ateee89 commented on src/ContentHub.php
> +      return self::getResponseJson($this->put("snapshots/$name/restore"));
Same here.

2020-11-09 20:50 UTC, abarriosr commented on src/ContentHub.php
> +      $endpoint = "$this->api_version/snapshots";
The only available version for this API call is `/v2`. Then all calls should use that instead of `$api_version`.

2020-11-11 13:27 UTC, Ateee89 approved these changes

2020-11-11 13:29 UTC, Ateee89 approved these changes

2020-11-11 13:31 UTC, merged