LCH-5024: Implement new interest list endpoint.
acquia/content-hub-php pull request #123
Opened 2021-08-11 10:08 UTC by saxumVermes

2021-08-17 14:54 UTC, jose-oliveira approved these changes

2021-08-18 08:48 UTC, ankitsingh0188 commented on src/ContentHubClient.php
> +  public function addEntitiesToInterestList($webhook_uuid, array $uuids) {
argument type and return type missing.

2021-08-18 08:48 UTC, ankitsingh0188 commented on src/ContentHubClient.php
> +  public function deleteInterest($uuid, $webhook_uuid) {
argument type & return type missing.

2021-08-18 08:48 UTC, ankitsingh0188 commented on src/ContentHubClient.php
> +  public function getSettings() {
return type missing.

2021-08-18 08:49 UTC, ankitsingh0188 requested changes
Left some minor comments, looks good otherwise.

2021-08-18 09:20 UTC, ankitsingh0188 approved these changes
Looks good to me!!

2021-08-18 13:06 UTC, amangrover90 approved these changes
Looks good to me!!

2021-08-18 13:07 UTC, merged