LCH-5312: Created filter functions and code refactor
acquia/content-hub-php pull request #124
Opened 2021-08-24 12:11 UTC by ankitsingh0188

2021-08-26 11:56 UTC, saxumVermes requested changes

2021-08-26 11:56 UTC, saxumVermes commented on src/ContentHubClient.php
> +  protected function getErrorResponse(int $code, string $reason, ?string $request_id = NULL): Response {
Use response interface instead as the return type.

2021-08-26 11:56 UTC, saxumVermes commented on src/ContentHubClient.php
> +  public function startScrollByFilter(string $filter_uuid, string $scroll_time_window, int $size) {
So although the json_decode can return objects too, we are actually command it to return an associative array. Please specify the return type accordingly.

2021-08-26 11:56 UTC, saxumVermes commented on src/ContentHubClient.php
> +  public function continueScroll(string $scroll_id, string $scroll_time_window) {
Same here about return types.

2021-08-26 11:56 UTC, saxumVermes commented on src/ContentHubClient.php
> +  public function cancelScroll(string $scroll_id) {
And here.

2021-08-26 11:56 UTC, saxumVermes commented on src/ContentHubClient.php
> +   *   suffixed with duration unit (m, s, ms etc.).
Hope we can get a response about that soon...

2021-08-26 11:56 UTC, saxumVermes commented on test/ContentHubClientTest.php
> +      'scroll' => '10m',
You can just use `$scroll_time_window` here too, can't you?

2021-08-26 11:56 UTC, saxumVermes commented on test/ContentHubClientTest.php
> +      ->with("scroll", ['body' => json_encode($request_parameters)])
Could you please use single quotes?

2021-08-26 13:47 UTC, ankitsingh0188 commented on src/ContentHubClient.php
> +   *   suffixed with duration unit (m, s, ms etc.).
Yeah, awaiting response from service team.

2021-08-27 09:25 UTC, saxumVermes approved these changes
Left a comment, there's an unnecessary import, please fix that, otherwise it's good to go.

2021-08-27 09:25 UTC, saxumVermes commented on src/ContentHubClient.php
>  use Symfony\Component\HttpFoundation\Response as SymfonyResponse;
I don't understand that, why is that we're importing the same object twice with different names?

2021-08-27 09:28 UTC, ankitsingh0188 commented on src/ContentHubClient.php
>  use Symfony\Component\HttpFoundation\Response as SymfonyResponse;
Done.

2021-08-27 10:03 UTC, amangrover90 approved these changes
Looks good to me!!

2021-08-27 10:05 UTC, merged