LCH-5270: Added new method query entities
acquia/content-hub-php pull request #133
Opened 2021-10-21 08:13 UTC by ankitsingh0188

2021-10-21 08:15 UTC, ankitsingh0188 commented
Build will fail because we need to merge the https://github.com/acquia/content-hub-php/pull/133 PHP Lib PR first.

2021-10-21 15:35 UTC, saxumVermes requested changes
We need to follow-up on the change in ObjectFastory::getCHClient() as well.

2021-10-21 15:35 UTC, saxumVermes commented on src/ContentHubClient.php
> +    return self::getResponseJson($this->get("entities", [RequestOptions::QUERY => $params]));
Please use single quotes.

2021-10-21 15:35 UTC, saxumVermes commented on src/ContentHubClient.php
> +   * Fetch entities via query params.
```suggestion
   * Fetches entities via query params.
```

2021-10-21 15:35 UTC, saxumVermes commented on src/ContentHubClient.php
> +  public function queryEntities(array $params): ?array {
Let's make this parameter optional.

2021-10-21 15:35 UTC, saxumVermes commented on src/ContentHubClient.php
> +   *   Query params.
Let's include the expected array structure into the documentation like:
```php
 [ 'param1' => 'param_value' ]
```

2021-10-21 17:10 UTC, saxumVermes commented on test/ContentHubClientTest.php
> +  }
After we made the array parameter optional, we need another test case, testing without any argument passed to the `queryEntities` method.

2021-10-22 06:15 UTC, ankitsingh0188 commented on test/ContentHubClientTest.php
> +  }
Done.

2021-10-22 06:15 UTC, ankitsingh0188 commented on src/ContentHubClient.php
> +  public function queryEntities(array $params): ?array {
Done.

2021-10-22 06:15 UTC, ankitsingh0188 commented on src/ContentHubClient.php
> +   * Fetch entities via query params.
Done.

2021-10-22 06:15 UTC, ankitsingh0188 commented on src/ContentHubClient.php
> +    return self::getResponseJson($this->get("entities", [RequestOptions::QUERY => $params]));
Done.

2021-10-22 06:15 UTC, ankitsingh0188 commented
> We need to follow-up on the change in ObjectFastory::getCHClient() as well.

Refactored the ObjectFactory::getCHClient() method and it's usage.

2021-10-22 06:16 UTC, ankitsingh0188 commented on src/ContentHubClient.php
> +   *   Query params.
Sure.

2021-10-22 13:55 UTC, saxumVermes commented on src/ContentHubClient.php
> +use GuzzleHttp\RequestOptions;
Thanks for removing the unused imports!

2021-10-22 13:58 UTC, saxumVermes approved these changes
Looks good, let's roll it!

2021-10-22 14:17 UTC, ankitsingh0188 commented on src/ContentHubClient.php
> +use GuzzleHttp\RequestOptions;
My Pleasure 👍

2021-10-22 14:19 UTC, amangrover90 approved these changes
Looks good to me!!

2021-10-22 14:19 UTC, merged