LCH-6425: Method to update webhook data in settings.
acquia/content-hub-php pull request #174
Opened 2023-04-19 14:03 UTC by narendradesai

2023-04-20 12:26 UTC, saxumVermes requested changes

2023-04-20 12:26 UTC, saxumVermes commented on src/Settings.php
> +  public function updateWebhook(array $webhook): void {
I feel like we need to search for another solution. This would violate the purpose of this class, which is being an immutable object.

2023-04-20 12:27 UTC, saxumVermes commented on src/Settings.php
> +  public function updateWebhook(array $webhook): void {
One its attributes of an immutable object is to preserve state and avoid any side effects.

2023-04-21 13:20 UTC, closed without merging

2023-04-21 13:20 UTC, narendradesai commented
Closing this PR as it is not necessary.