LCH-6790-2.x : Port maintenance mode changes
acquia/content-hub-php pull request #187
Opened 2023-11-30 13:43 UTC by kirtigarg2584

**Motivation**

Fixes #NNN

**Proposed changes**

**Alternatives considered**

**Testing steps**

2023-12-04 14:16 UTC, saxumVermes commented on src/ContentHubLoggingClient.php
We don't need the logging client in 2.x version of the module, because it doesn't utilize the event service. That only become available in 3.x version of the module.

2023-12-04 14:16 UTC, saxumVermes commented on src/ContentHubLoggingClientInterface.php
And we are not going to need this either.

2023-12-04 14:16 UTC, saxumVermes commented on src/ContentHubClientCommonTrait.php
> +    private ResponseInterface $response;
In this version of the library we still support 7.3. That would break backward compatibility.

2023-12-04 14:16 UTC, saxumVermes commented on src/ContentHubDescriptor.php
We don't need that class either, because it is only used in ContentHubLoggingClient.

2023-12-04 14:16 UTC, saxumVermes commented on src/Syndication/SyndicationEvents.php
We dont' need this either, because it is related to event service.

2023-12-04 14:17 UTC, saxumVermes commented on src/Syndication/SyndicationStatus.php
We can remove this too.

2023-12-04 14:20 UTC, saxumVermes commented on src/ContentHubClientCommonTrait.php
> +    private ResponseInterface $response;
In this version of the library we still support 7.3. That would break backward compatibility.

2023-12-04 14:21 UTC, saxumVermes commented on src/ContentHubClient.php
> +
These can be removed, we are not using these functions. They're supposed to only exist in 3.x version.

2023-12-04 14:22 UTC, narendradesai requested changes
There are unnecessary file changes in this PR. Need to refactor it. Will work on this in morning.

2023-12-04 14:22 UTC, saxumVermes commented on src/Logging/LoggingHelperTrait.php
> +  public LoggerInterface $logger;
In this version of the library we still support 7.3. That would break backward compatibility.

2023-12-04 14:26 UTC, saxumVermes reviewed
@kirtigarg2584 By looking through the code, tbh I think the only necessary change in this PR is to add the new request observer function through which we can retrieve the last response.

2023-12-05 07:53 UTC, narendradesai commented
@saxumVermes @kirtigarg2584 ,  I've created a separate PR for Porting maintenance mode changes to 2.x: https://github.com/acquia/content-hub-php/pull/191

2023-12-05 16:42 UTC, closed without merging