LCH-6737 : deleteMultipleInterest method added
acquia/content-hub-php pull request #194
Opened 2024-01-25 16:06 UTC by kirtigarg2584

**Motivation**

Fixes #NNN

**Proposed changes**

**Alternatives considered**

**Testing steps**

2024-01-29 13:28 UTC, saxumVermes commented on test/ContentHubClientTest.php
> +  public function testDeleteMultipleInterest(): void { // phpcs:ignore
Why do we need to ignore this line?

2024-01-29 14:01 UTC, saxumVermes requested changes

2024-01-29 14:01 UTC, saxumVermes commented on test/ContentHubClientTest.php
> +      ->with("v2/interest/{$webhook_uuid}/{$site_role}", ['body' => json_encode($interest_list)])
Curly braces are not necessary in this case.

2024-01-29 14:01 UTC, saxumVermes commented on test/ContentHubClientTest.php
> +      ->with("v2/interest/{$webhook_uuid}/{$site_role}", ['body' => json_encode($interest_list)])
neither here.

2024-01-29 14:01 UTC, saxumVermes commented on src/ContentHubClient.php
> +  public function deleteMultipleInterest(string $webhook_uuid, array $interest_list, string $site_role): ResponseInterface {
I think it should be enough just to pass the uuids to delete as the #2 argument instead of this structure:
```php
$interest_list['uuids'] = ['uuid1', 'uuid2'];
```
What do you think? It produces a cleaner API.

2024-01-29 14:01 UTC, saxumVermes commented on test/ContentHubClientTest.php
> +    $interest_list['uuids'][] = $this->test_data['uuid'] . ',some-uuid-2,some-uuid-3,';
This should be a list of uuids, not 1 element of concatenated uuids.

2024-01-31 11:26 UTC, narendradesai approved these changes
Looks good

2024-01-31 13:48 UTC, narendradesai commented on src/ContentHubClient.php
> +  public function deleteMultipleInterest(string $webhook_uuid, array $interest_list, string $site_role): ResponseInterface {
$options['body']['uuids'] = json_encode($interest_list)

2024-01-31 18:24 UTC, saxumVermes approved these changes
Looks good, thanks @kirtigarg2584!

2024-01-31 18:24 UTC, merged